# Generated by Django 3.2.3 on 2021-05-17 17:17

from django.db import migrations, models
import encrypted_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', encrypted_fields.fields.EncryptedCharField(max_length=40)),
            ],
        ),
    ]
