# Generated by Django 3.2.3 on 2021-05-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_detect',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_face_swap',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo_pointillism',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
